feat: tmux-sessionizer can clone github repos

diff --git a/bin/tmux-sessionizer b/bin/tmux-sessionizer
--- a/bin/tmux-sessionizer
+++ b/bin/tmux-sessionizer
@@ -20,15 +20,37 @@ if [[ -z $selected ]]; then
     exit 0
 fi
 
-# If the selected path doesn't exist and it's not "default", create it
 if [[ ! -d $selected ]] && [[ $selected != "default" ]]; then
-    read -p "Directory '${WORK_DIR}/$selected' doesn't exist. Create it? (y/n) " -n 1 -r
-    echo
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        mkdir -p "${WORK_DIR}/$selected"
-        selected="${WORK_DIR}/$selected"
+    # Check if the input is a GitHub URL
+    if [[ $selected == https://github.com/* || $selected == git@github.com:* ]]; then
+        # It's a GitHub URL, extract the repo name from the URL
+        repo_name=$(basename "$selected" .git)
+        read -p "Clone GitHub repo to '${WORK_DIR}/$repo_name'? Enter new directory name or press enter to use '$repo_name': " custom_name
+
+        if [[ -n $custom_name ]]; then
+            target_dir="${WORK_DIR}/$custom_name"
+        else
+            target_dir="${WORK_DIR}/$repo_name"
+        fi
+
+        git clone "$selected" "$target_dir"
+        if [[ $? -eq 0 ]]; then
+            echo "Repository cloned successfully to $target_dir"
+            selected="$target_dir"
+        else
+            echo "Failed to clone repository"
+            exit 1
+        fi
     else
-        exit 0
+        # It's a directory path, offer to create it
+        read -p "Directory '${WORK_DIR}/$selected' doesn't exist. Create it? (y/n) " -n 1 -r
+        echo
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            mkdir -p "${WORK_DIR}/$selected"
+            selected="${WORK_DIR}/$selected"
+        else
+            exit 0
+        fi
     fi
 fi
 
