Add yabai symlink, update symlink logic

diff --git a/mklinks b/mklinks
--- a/mklinks
+++ b/mklinks
@@ -4,6 +4,11 @@ create_symlink() {
     local target_file=$1
     local link_file=$2
 
+    if [ ! -f "$target_file" ]; then
+        echo "File not found: $target_file"
+        exit 1
+    fi
+
     if [ -L "$link_file" ]; then
         unlink "$link_file"
     fi
@@ -39,6 +44,7 @@ setup_common_symlinks() {
     create_symlink "$DOTFILES_DIR/zshrc/aliases.zsh" "$HOME/.oh-my-zsh/custom/aliases.zsh"
     if [[ "$OSTYPE" == "darwin"* ]]; then
         create_symlink "$DOTFILES_DIR/macos/DefaultKeyBinding.dict" "$HOME/Library/KeyBindings/DefaultKeyBinding.dict"
+        create_symlink "$DOTFILES_DIR/yabai" "$HOME/.config/yabai"
     fi
 }
 
